package com.stockpulse.service;

import com.stockpulse.domain.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AdvisoryPersistenceService {
    
    @Autowired
    private PricingSuggestionRepository pricingSuggestionRepository;
    
    @Autowired
    private ReorderSuggestionRepository reorderSuggestionRepository;
    
    /**
     * Persist the pricing and reorder suggestions generated by the CommerceAdvisor
     */
    @Transactional
    public void persistAdvisoryResult(AdvisoryResult result) {
        // Save pricing suggestion
        if (result.getPricingSuggestion() != null) {
            pricingSuggestionRepository.save(result.getPricingSuggestion());
        }
        
        // Save reorder suggestion
        if (result.getReorderSuggestion() != null) {
            reorderSuggestionRepository.save(result.getReorderSuggestion());
        }
    }
    
    /**
     * Save only the pricing suggestion
     */
    @Transactional
    public PricingSuggestion savePricingSuggestion(PricingSuggestion suggestion) {
        return pricingSuggestionRepository.save(suggestion);
    }
    
    /**
     * Save only the reorder suggestion
     */
    @Transactional
    public ReorderSuggestion saveReorderSuggestion(ReorderSuggestion suggestion) {
        return reorderSuggestionRepository.save(suggestion);
    }
}